### ISSUE TITLE
translate shut-down message into German

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/pledgebank#107]
Lots of Pledgebank's  active users are German-speakers so if we can get the banner into German for that would be a kindness.
http://www.de.pledgebank.com/

translation of #102 

>  With regret, we’ve made the difficult decision to close this site
>  down from the end of June.
> You can still browse and sign existing pledges, but you can no
> longer create new ones. Find out more…

**Comment by dracos** [comment]
Too late
