### ISSUE TITLE
Remove all microsites config from poster.cgi

### ISSUE THREAD

**Issue by osfameron** [mysociety/pledgebank#98]
Currently to make microsites config changes, you have to make them in `phplib/microsites.php` _and_ `web/poster.cgi`.  As the latter is a python script, it doesn't have access to PHP libs.

Should refactor poster.cgi into:
- poster.php which handles all microsite config and translates it into display config (with xss protection as required)
- poster.cgi should only read this display config.

**Comment by dracos** [comment]
Site archived.
